import { BusinessOpportunity } from "@/types/master-models";

export const DEMO_BUSINESS_OPPORTUNITIES: BusinessOpportunity[] = [
  {
    id: "biz-01",
    postedByMemberId: "mem-06",
    posterName: "Bethlehem Tadesse",
    posterCompany: "Horn of Africa Organic Exports",
    category: "Food Export Networks",
    country: "Ethiopia",
    title: "Distribution Partnership for Certified Grade-1 Specialty Coffee across ECOWAS & SADC",
    description: "Seeking established regional food & beverage distributors in Nigeria, Ghana, South Africa, and Kenya to carry direct container loads of roasted and green Yirgacheffe & Guji organic coffee under AfCFTA preferential tariffs.",
    investmentRange: "$50,000 – $250,000 USD",
    contactInfo: "trade@hornofafrica-exports.com",
    createdAt: "2025-07-28",
    status: "Open",
  },
  {
    id: "biz-02",
    postedByMemberId: "mem-02",
    posterName: "Kwame Mensah",
    posterCompany: "Ashanti Cocoa Processing Ventures",
    category: "Agribusiness Investments",
    country: "Ghana",
    title: "Joint Venture for Solar-Powered Cocoa Butter & Powder Extraction Facility (Kumasi)",
    description: "Raising co-investment for a 500-ton annual capacity solar micro-processing plant to eliminate diesel dependency and produce premium single-origin certified fair trade butter for African confectionery brands.",
    investmentRange: "$150,000 – $500,000 USD",
    contactInfo: "kwame.mensah@accf-demo.africa",
    createdAt: "2025-08-05",
    status: "Open",
  },
  {
    id: "biz-03",
    postedByMemberId: "mem-03",
    posterName: "Ambassador Wanjiku Mwangi",
    posterCompany: "Great Rift Valley Cold-Chain Logistics",
    category: "Food Technology",
    country: "Kenya",
    title: "Expansion of Off-Grid Solar Cold Hubs for Horticultural Smallholders in Narok & Meru",
    description: "Deploying 20 modular pay-as-you-store solar chill rooms to reduce post-harvest losses from 40% to under 5% for indigenous leafy greens, tomatoes, and passion fruit. Seeking debt or equity financing partners.",
    investmentRange: "$200,000 – $750,000 USD",
    contactInfo: "invest@riftvalley-coldchain.ke",
    createdAt: "2025-08-11",
    status: "In Negotiation",
  },
  {
    id: "biz-04",
    postedByMemberId: "mem-01",
    posterName: "Amina Okafor",
    posterCompany: "Heritage Grains Trust",
    category: "Trade Partnerships",
    country: "Nigeria",
    title: "Contract Farming Supply Agreement for 1,000 Hectares of Heirloom Fonio & Bambara Groundnut",
    description: "Connecting institutional food manufacturers and plant-based protein producers with certified women-led farming cooperatives across Kebbi and Kaduna states for guaranteed off-take.",
    investmentRange: "₦50,000,000 – ₦180,000,000 NGN",
    contactInfo: "partnerships@heritagegrains.ng",
    createdAt: "2025-08-16",
    status: "Open",
  },
];

