import { CountryProfile } from "@/types/master-models";

export const DEMO_COUNTRIES: CountryProfile[] = [
  {
    code: "NG",
    name: "Nigeria",
    region: "West Africa",
    flagEmoji: "🇳🇬",
    capital: "Abuja",
    signatureDish: "Smoked Jollof Rice & Egusi with Pounded Yam",
    dishDescription: "Iconic firewood-smoked long-grain rice infused with scotch bonnet, tomatoes, and Nigerian bay leaf, paired with melon-seed rich soup.",
    foodHeritageBrief: "Nigeria's culinary landscape spans over 250 ethnic nationalities, celebrated for complex fermentation, deep umami soups, and ancient yam cultivation rituals.",
    traditionalIngredients: ["Iru (Fermented Locust Beans)", "Crayfish", "Egusi Seeds", "Scotch Bonnet (Ata Rodo)", "Bitterleaf", "Kolanut"],
    membersCount: 84200,
    hostsCount: 420,
    productsCount: 180,
    peaceSignatures: 1250000,
    coverImage: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "GH",
    name: "Ghana",
    region: "West Africa",
    flagEmoji: "🇬🇭",
    capital: "Accra",
    signatureDish: "Authentic Waakye with Shito & Fried Plantain",
    dishDescription: "Fragrant rice and cowpeas cooked with dried sorghum leaves for a rich burgundy hue, accompanied by dark smoked chili fish sauce (Shito).",
    foodHeritageBrief: "From the coastal fishing villages to the Ashanti highlands, Ghanaian cuisine balances sweet caramelized plantains with intensely spicy pepper sauces.",
    traditionalIngredients: ["Shito Pepper", "Prekese (Aidan Fruit)", "Dawadawa", "Cassava & Green Plantain (Fufu)", "Smoked Herrings"],
    membersCount: 52100,
    hostsCount: 290,
    productsCount: 120,
    peaceSignatures: 890000,
    coverImage: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "KE",
    name: "Kenya",
    region: "East Africa",
    flagEmoji: "🇰🇪",
    capital: "Nairobi",
    signatureDish: "Nyama Choma with Sukuma Wiki & Ugali",
    dishDescription: "Slow wood-roasted goat meat with flame-blistered crust, served with braised collard greens, sweet diced Kachumbari salsa, and stiff white maize ugali.",
    foodHeritageBrief: "A dynamic fusion of Great Rift Valley pastoralist traditions and ancient Swahili coastal maritime spice influences along the Indian Ocean.",
    traditionalIngredients: ["Sukuma Wiki", "Kachumbari", "Mursik (Fermented Milk)", "Green Cardamom", "Coconut Milk", "Dhania"],
    membersCount: 48900,
    hostsCount: 260,
    productsCount: 95,
    peaceSignatures: 740000,
    coverImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "ET",
    name: "Ethiopia",
    region: "East Africa",
    flagEmoji: "🇪🇹",
    capital: "Addis Ababa",
    signatureDish: "Doro Wat on Sourdough Teff Injera",
    dishDescription: "Slow-simmered caramelized onion and tender chicken stew seasoned with Berbere spice blend, served on a porous fermented Teff flatbread.",
    foodHeritageBrief: "One of the world's most ancient unbroken culinary traditions, renowned for communal platter dining (Gursha) and the birthplace of Arabica coffee.",
    traditionalIngredients: ["Teff Grain", "Berbere Spice", "Niter Kibbeh (Spiced Butter)", "Korerima (Black Cardamom)", "Koseret"],
    membersCount: 46200,
    hostsCount: 240,
    productsCount: 88,
    peaceSignatures: 810000,
    coverImage: "https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "RW",
    name: "Rwanda",
    region: "East Africa",
    flagEmoji: "🇷🇼",
    capital: "Kigali",
    signatureDish: "Isambaza with Matoke & Akabanga Chili",
    dishDescription: "Delicate fresh Lake Kivu silver fish crisp-fried with onions and served alongside steamed savory green cooking bananas and legendary hot chili oil.",
    foodHeritageBrief: "The Land of a Thousand Hills celebrates volcanic soil fertility, mountain legumes, and community-driven solidarity through shared dining.",
    traditionalIngredients: ["Akabanga Chili", "Lake Kivu Isambaza", "Matoke Bananas", "Red Kidney Beans", "Ubugali"],
    membersCount: 31000,
    hostsCount: 150,
    productsCount: 65,
    peaceSignatures: 480000,
    coverImage: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "ZA",
    name: "South Africa",
    region: "Southern Africa",
    flagEmoji: "🇿🇦",
    capital: "Pretoria / Cape Town",
    signatureDish: "Cape Malay Bobotie & Potjiekos",
    dishDescription: "Aromatic baked spiced minced meat custard with bay leaves and golden raisins, alongside three-legged cast-iron slow braised wild venison.",
    foodHeritageBrief: "A vibrant culinary crossroads uniting indigenous Khoisan, Bantu braai techniques, Cape Malay spice heritage, and farm-to-table coastal cuisine.",
    traditionalIngredients: ["Rooibos", "Cape Malay Curry Powder", "Mrs. Ball's Chutney", "Mealie Pap", "Samp & Beans", "Biltong"],
    membersCount: 61400,
    hostsCount: 310,
    productsCount: 140,
    peaceSignatures: 960000,
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "SN",
    name: "Senegal",
    region: "West Africa",
    flagEmoji: "🇸🇳",
    capital: "Dakar",
    signatureDish: "Thieboudienne (Ceebu Jën)",
    dishDescription: "UNESCO-inscribed national dish of broken jasmine rice simmered in rich tomato broth with white fish, tamarind, cassava, pumpkin, and stuffed herbs.",
    foodHeritageBrief: "The epicenter of West African Teranga (hospitality), where communal round-bowl dining transforms every meal into a celebration of fraternity.",
    traditionalIngredients: ["Netetou", "Dried Conch (Yeet)", "Bissap (Hibiscus)", "Tamarind", "Broken Jasmine Rice", "Guedj (Fermented Dried Fish)"],
    membersCount: 38500,
    hostsCount: 195,
    productsCount: 80,
    peaceSignatures: 610000,
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "MA",
    name: "Morocco",
    region: "North Africa",
    flagEmoji: "🇲🇦",
    capital: "Rabat",
    signatureDish: "Slow-Cooked Lamb Tagine with Prunes & Toasted Almonds",
    dishDescription: "Conical clay pot slow-braised tender lamb shoulder infused with saffron, ginger, cinnamon, golden honey, and caramelized Agen prunes.",
    foodHeritageBrief: "An opulent imperial culinary heritage intertwining Berber agrarian staples, Mediterranean olive groves, and historic trans-Saharan spice routes.",
    traditionalIngredients: ["Ras el Hanout", "Saffron from Taliouine", "Preserved Lemons", "Argan Oil", "Orange Blossom Water", "Smén"],
    membersCount: 42800,
    hostsCount: 220,
    productsCount: 110,
    peaceSignatures: 690000,
    coverImage: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "EG",
    name: "Egypt",
    region: "North Africa",
    flagEmoji: "🇪🇬",
    capital: "Cairo",
    signatureDish: "Authentic Egyptian Koshari & Ful Medames",
    dishDescription: "Hearty vegetarian tapestry of rice, brown lentils, macaroni, spiced chickpeas, crispy fried onions, and garlic-vinegar chili tomato sauce.",
    foodHeritageBrief: "5,000 years of unbroken Nile Valley agronomy, preserving ancient grain sourdoughs, fava bean stews, and fragrant sesame tahini sauces.",
    traditionalIngredients: ["Fava Beans (Ful Medames)", "Baladi Sourdough", "Molokhia Leaves", "Dukkah", "Nigella Seeds", "Date Molasses"],
    membersCount: 49000,
    hostsCount: 250,
    productsCount: 90,
    peaceSignatures: 780000,
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "TZ",
    name: "Tanzania",
    region: "East Africa",
    flagEmoji: "🇹🇿",
    capital: "Dodoma / Dar es Salaam",
    signatureDish: "Zanzibari Seafood Coconut Curry & Pilau",
    dishDescription: "Fragrant rice cooked in beef broth with whole cardamom, cloves, and cinnamon, served with fresh Indian Ocean lobster in thick spiced coconut gravy.",
    foodHeritageBrief: "Home to the Spice Islands of Zanzibar, uniting East African inland harvests with centuries of Swahili maritime spice cultivation.",
    traditionalIngredients: ["Zanzibar Cloves", "Fresh Coconut Milk", "Pilau Masala", "Cardamom", "Cassava Leaves (Mchicha)"],
    membersCount: 39700,
    hostsCount: 180,
    productsCount: 85,
    peaceSignatures: 580000,
    coverImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "CM",
    name: "Cameroon",
    region: "Central Africa",
    flagEmoji: "🇨🇲",
    capital: "Yaoundé",
    signatureDish: "Royal Ndolé with Smoked Fish & Fried Plantains",
    dishDescription: "Slow-cooked stew of bitterleaf, ground raw peanuts, smoked fish, and fresh prawns, served with boiled cassava rods (Bobolo).",
    foodHeritageBrief: "Known as 'Africa in Miniature', showcasing pristine Congo basin forest ingredients, volcanic soil tubers, and Atlantic coast seafood.",
    traditionalIngredients: ["Penja White Pepper", "Ndolé (Bitterleaf)", "Bobolo (Cassava Miondo)", "Djansang Seeds", "Country Onions"],
    membersCount: 34100,
    hostsCount: 160,
    productsCount: 75,
    peaceSignatures: 520000,
    coverImage: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    region: "West Africa",
    flagEmoji: "🇨🇮",
    capital: "Yamoussoukro / Abidjan",
    signatureDish: "Garba & Braised Capitaine Fish with Fresh Attieke",
    dishDescription: "Steamed fermented cassava couscous accompanied by crispy seasoned tuna steak, fresh chopped tomatoes, onions, and spicy piment.",
    foodHeritageBrief: "The world's leading cocoa producer, boasting vibrant street food culture, forest gastronomy, and coastal Akan culinary traditions.",
    traditionalIngredients: ["Attieke (Fermented Cassava Couscous)", "Soumbara", "Piment Antillais", "Akpi Seeds", "Palm Oil"],
    membersCount: 36200,
    hostsCount: 175,
    productsCount: 70,
    peaceSignatures: 550000,
    coverImage: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "UG",
    name: "Uganda",
    region: "East Africa",
    flagEmoji: "🇺🇬",
    capital: "Kampala",
    signatureDish: "Matooke in Luwombo with Groundnut Sauce",
    dishDescription: "Steamed, mashed savory green bananas served with smoked beef or free-range chicken steamed inside tender banana leaves with rich peanut paste.",
    foodHeritageBrief: "The Pearl of Africa, known for year-round fertile green harvests, sweet tropical fruits, and ancestral royal Buganda cooking methods.",
    traditionalIngredients: ["Matooke", "Smoked Groundnuts", "Ekitobeero Herbs", "Simsim (Sesame)", "Lake Victoria Nile Perch"],
    membersCount: 28900,
    hostsCount: 140,
    productsCount: 55,
    peaceSignatures: 430000,
    coverImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "ZM",
    name: "Zambia",
    region: "Southern Africa",
    flagEmoji: "🇿🇲",
    capital: "Lusaka",
    signatureDish: "Nshima with Village Chicken & Chibwabwa",
    dishDescription: "Stiff white cornmeal porridge paired with tender free-range chicken in rich onion-tomato gravy and braised pumpkin leaves in crushed peanut powder.",
    foodHeritageBrief: "Zambian cuisine celebrates wild indigenous forest tubers, wild mushrooms from the Miombo woodlands, and freshwater bream from Lake Kariba.",
    traditionalIngredients: ["Chibwabwa (Pumpkin Leaves)", "Chikanda (African Polony)", "Kapenta (Small Dried Fish)", "Ifinkubala (Mopane Worms)"],
    membersCount: 22400,
    hostsCount: 110,
    productsCount: 40,
    peaceSignatures: 340000,
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    region: "Southern Africa",
    flagEmoji: "🇿🇼",
    capital: "Harare",
    signatureDish: "Sadza with Oxtail & Muriwo une Dovi",
    dishDescription: "Fluffy white maize porridge served with slow-cooked unctuous oxtail and braised dark leafy greens enriched with pure roasted peanut butter.",
    foodHeritageBrief: "Steeped in Great Zimbabwe architectural heritage, honoring ancient dry-land grains like finger millet (Zviyo) and sorghum.",
    traditionalIngredients: ["Zviyo (Finger Millet)", "Dovi (Peanut Butter)", "Madora (Mopane)", "Nyimo (Bambara Groundnuts)"],
    membersCount: 24500,
    hostsCount: 120,
    productsCount: 45,
    peaceSignatures: 370000,
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "BW",
    name: "Botswana",
    region: "Southern Africa",
    flagEmoji: "🇧🇼",
    capital: "Gaborone",
    signatureDish: "Seswaa with Pap & Morogo",
    dishDescription: "Ceremonial pounded slow-boiled beef prepared in a cast-iron pot over open wood fire with simple coarse salt, accompanied by wild spinach.",
    foodHeritageBrief: "Setswana culinary pride centers on free-range grass-fed Kalahari beef, sorghum porridge (Bogobe), and indigenous Kalahari desert melons.",
    traditionalIngredients: ["Seswaa Beef", "Bogobe jwa Ting (Fermented Sorghum)", "Morogo wa Dinawa", "Dikgobe"],
    membersCount: 18200,
    hostsCount: 90,
    productsCount: 35,
    peaceSignatures: 280000,
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "NA",
    name: "Namibia",
    region: "Southern Africa",
    flagEmoji: "🇳🇦",
    capital: "Windhoek",
    signatureDish: "Kapana with Oshifima & Chakalaka",
    dishDescription: "Street-grilled tender sliced beef tossed in spicy chili salt (Kapana spice), eaten with Oshifima pearl millet porridge and spicy vegetable relish.",
    foodHeritageBrief: "An extraordinary blend of Owambo agrarian pearl millet farming, Herero cattle traditions, and pristine Atlantic oysters from Walvis Bay.",
    traditionalIngredients: ["Mahangu (Pearl Millet)", "Kapana Spice Mix", "Onyeni Leaf Relish", "!Nara Melon Oil"],
    membersCount: 17100,
    hostsCount: 85,
    productsCount: 30,
    peaceSignatures: 250000,
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "BJ",
    name: "Benin",
    region: "West Africa",
    flagEmoji: "🇧🇯",
    capital: "Porto-Novo / Cotonou",
    signatureDish: "Amiwo with Guinea Fowl & Crushed Chili",
    dishDescription: "Red corn flour paste cooked in seasoned tomato and chicken broth, served with wood-smoked crispy guinea fowl and fiery green pepper condiment.",
    foodHeritageBrief: "Cradle of Dahomey royal culinary arts, famed for fermented heirloom corn doughs, vibrant lagoon fisheries, and sacred palm oil preparations.",
    traditionalIngredients: ["Afitin (Fermented Néré)", "Akassa Corn Dough", "Gboma Leaves", "Red Palm Oil", "Sodabi Extract"],
    membersCount: 19800,
    hostsCount: 95,
    productsCount: 42,
    peaceSignatures: 310000,
    coverImage: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "LR",
    name: "Liberia",
    region: "West Africa",
    flagEmoji: "🇱🇷",
    capital: "Monrovia",
    signatureDish: "Liberian Pepper Soup & Palm Butter Rice",
    dishDescription: "Rich palm pulp soup slow-cooked with fresh crab, smoked catfish, and country spices, served over mountain upland country rice.",
    foodHeritageBrief: "A unique coastal harmony of indigenous Kru fishing traditions, rainforest wild herbs, and transatlantic returnee influences.",
    traditionalIngredients: ["Palm Butter Pulp", "Country Rice", "Bitterball (African Eggplant)", "Kittily Seeds", "Country Spices"],
    membersCount: 15400,
    hostsCount: 75,
    productsCount: 28,
    peaceSignatures: 230000,
    coverImage: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    region: "West Africa",
    flagEmoji: "🇸🇱",
    capital: "Freetown",
    signatureDish: "Cassava Leaf Stew with Steamed Rice",
    dishDescription: "Tender pounded cassava leaves simmered for hours with smoked fish, beef cuts, peanut butter paste, and hot red palm oil.",
    foodHeritageBrief: "Renowned for complex green-leaf stews (Plassas), sweet fried plantain snacks, and rich coastal seafood seasonings.",
    traditionalIngredients: ["Cassava Leaves", "Ogiri (Fermented Sesame)", "Dry Bonga Fish", "Red Palm Oil", "Krio Seasonings"],
    membersCount: 16200,
    hostsCount: 80,
    productsCount: 30,
    peaceSignatures: 240000,
    coverImage: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&auto=format&fit=crop&q=80",
  },
];

