import { FestivalEvent } from "@/types/master-models";

export const DEMO_FESTIVAL_EVENTS: FestivalEvent[] = [
  {
    id: "fest-01",
    name: "African Cuisine Expo 2026",
    subEventType: "cuisine-expo",
    description: "Experience the magnificent culinary diversity of 54 African nations under one grand canopy. 1,000 live cooking pavilions, master fermenters, ancestral grain milling, and street food tastings.",
    date: "October 14–18, 2026",
    time: "09:00 – 19:00 WAT Daily",
    venueLocation: "Eagle Square International Pavilion, Abuja, Nigeria",
    hallName: "Grand Continental Pavilion A & B",
    capacity: 25000,
    registeredCount: 14200,
    speakers: [
      { name: "Dr. Alimatu Bello", role: "Festival Executive Director", country: "Nigeria", photoUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80" },
      { name: "Chef Pierre Thiam", role: "Fonio Ambassador & Master Chef", country: "Senegal", photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80" },
    ],
    chefs: [
      { name: "Chef Fatou Diop", specialty: "Senegalese Royal Teranga", country: "Senegal", photoUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80" },
      { name: "Chef Samuel Abebe", specialty: "Ethiopian Sourdough & Berbere", country: "Ethiopia", photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80" },
      { name: "Chef Amina Okafor", specialty: "West African Heritage Soups", country: "Nigeria", photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80" },
    ],
    coverImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "fest-02",
    name: "Pan-African Chefs Championship",
    subEventType: "chefs-championship",
    description: "The premier competitive culinary tournament in Africa. Top chefs from 54 nations compete live in black-box challenges utilizing exclusively indigenous African ingredients, ancient grains, and heritage cookery techniques.",
    date: "October 15–17, 2026",
    time: "14:00 – 18:00 WAT",
    venueLocation: "Culinary Arena 1, Eagle Square, Abuja",
    hallName: "Master Chef Stadium",
    capacity: 5000,
    registeredCount: 3890,
    speakers: [
      { name: "Chef Thabo Mokoena", role: "Head of Judging Jury", country: "South Africa", photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80" },
    ],
    chefs: [
      { name: "Chef Tariq El-Mansouri", specialty: "North African Spice Architect", country: "Morocco", photoUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80" },
      { name: "Chef Zuwena Said", specialty: "Swahili Coastal Aromatics", country: "Tanzania", photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80" },
    ],
    coverImage: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "fest-03",
    name: "Food Security & Climate Summit",
    subEventType: "food-security-summit",
    description: "High-level ministerial policy plenary on shaping Africa's food sovereignty, scaling intra-African agricultural trade corridors, climate-resilient seed preservation, and post-harvest technology investment.",
    date: "October 14–15, 2026",
    time: "10:00 – 16:30 WAT",
    venueLocation: "Abuja International Conference Centre",
    hallName: "Africa Plenary Hall",
    capacity: 3500,
    registeredCount: 2900,
    speakers: [
      { name: "Ambassador Wanjiku Mwangi", role: "Lead Policy Rapporteur", country: "Kenya", photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80" },
      { name: "Kwame Mensah", role: "Agribusiness Trade Coordinator", country: "Ghana", photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80" },
    ],
    chefs: [],
    coverImage: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "fest-04",
    name: "African Cultural Village & Music Stage",
    subEventType: "cultural-village",
    description: "Immersive architectural pavilions representing Africa's major cultural dynasties: Ashanti, Yoruba, Zulu, Nubian, Great Zimbabwe, Swahili, and Dogon. Traditional live drumming, fashion pageants, and craft demonstrations.",
    date: "October 14–18, 2026",
    time: "11:00 – 23:00 WAT Daily",
    venueLocation: "Millennium Park Grounds, Abuja",
    hallName: "Heritage Village Open Grounds",
    capacity: 30000,
    registeredCount: 19800,
    speakers: [],
    chefs: [],
    coverImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
  },
  {
    id: "fest-05",
    name: "On-Site African Food Marketplace",
    subEventType: "marketplace",
    description: "Physical manifestation of the digital marketplace. 500 verified African agro-processors, spice artisans, indigenous textile weavers, and cold-pressed oil producers trading live with regional distributors.",
    date: "October 14–18, 2026",
    time: "09:00 – 20:00 WAT Daily",
    venueLocation: "Eagle Square South Wing",
    hallName: "B2B Trade Concourse",
    capacity: 15000,
    registeredCount: 8900,
    speakers: [
      { name: "Akosua Boateng", role: "Artisanal Guild Chairperson", country: "Ghana", photoUrl: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=400&auto=format&fit=crop&q=80" },
    ],
    chefs: [],
    coverImage: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
  },
  {
    id: "fest-06",
    name: "Youth Agri-Food Innovation Forum",
    subEventType: "youth-innovation",
    description: "Empowering 5,000 young African entrepreneurs, drone-agronomists, solar cold-chain founders, and digital food creators with seed capital pitch stages and mentorship.",
    date: "October 16, 2026",
    time: "10:00 – 17:00 WAT",
    venueLocation: "Abuja Tech & Innovation Hub",
    hallName: "Future Africa Auditorium",
    capacity: 4000,
    registeredCount: 3100,
    speakers: [
      { name: "Sandrine Mugabo", role: "Youth Innovation Lead", country: "Rwanda", photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80" },
    ],
    chefs: [],
    coverImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
  },
  {
    id: "fest-07",
    name: "Women in Food Leadership Summit",
    subEventType: "women-leadership",
    description: "Honoring the women who produce 70% of Africa's food. Highlighting female cooperative founders, research scientists, master distillers, and culinary icons driving the continent's agricultural economy.",
    date: "October 17, 2026",
    time: "09:30 – 15:00 WAT",
    venueLocation: "Transcorp Hilton Grand Ballroom, Abuja",
    hallName: "Empowerment Hall",
    capacity: 2500,
    registeredCount: 2200,
    speakers: [
      { name: "Dr. Alimatu Bello", role: "Executive Chair", country: "Nigeria", photoUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80" },
      { name: "Bethlehem Tadesse", role: "Export Council Leader", country: "Ethiopia", photoUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&auto=format&fit=crop&q=80" },
    ],
    chefs: [],
    coverImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
  },
  {
    id: "fest-08",
    name: "Flagship Peace Dinner & Kolanut Ceremony",
    subEventType: "peace-dinner",
    description: "The monumental symbolic climax of ACCF 2026. The breaking of the sacred Kolanut by African elders and youth across the historic 2-Kilometre Peace Table, serving 10,000 guests with 1,000 traditional dishes.",
    date: "October 18, 2026",
    time: "18:00 – 23:30 WAT",
    venueLocation: "The 2-Kilometre Peace Table Boulevard, Abuja",
    hallName: "The Great Peace Table",
    capacity: 10000,
    registeredCount: 8400,
    speakers: [
      { name: "His Royal Majesty Oba Adeyeye", role: "Royal Patriarch", country: "Nigeria", photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80" },
      { name: "Dr. Alimatu Bello", role: "Host Director", country: "Nigeria", photoUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80" },
    ],
    chefs: [
      { name: "Chef Fatou Diop", specialty: "West African Platter", country: "Senegal", photoUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80" },
      { name: "Chef Samuel Abebe", specialty: "East African Platter", country: "Ethiopia", photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80" },
      { name: "Chef Tariq El-Mansouri", specialty: "North African Platter", country: "Morocco", photoUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80" },
      { name: "Chef Thabo Mokoena", specialty: "Southern African Platter", country: "South Africa", photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80" },
    ],
    coverImage: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
];

