import { Hub, HubPost } from "@/types/master-models";

export const DEMO_HUBS: Hub[] = [
  {
    id: "hub-01",
    category: "Food Heritage & Ancient Grains",
    slug: "food-heritage",
    description: "Preserving ancestral recipes, fermentation wisdom, Fonio, Teff, Sorghum, and Indigenous African botanicals.",
    iconName: "Wheat",
    color: "bg-amber-900/40 text-amber-300 border-amber-800/60",
    membersCount: 24500,
    postsCount: 1820,
  },
  {
    id: "hub-02",
    category: "Traditional Recipes & Culinary Secrets",
    slug: "traditional-recipes",
    description: "Step-by-step masterclasses, home cooking techniques, spice blending ratios, and mother sauces from all 54 nations.",
    iconName: "UtensilsCrossed",
    color: "bg-emerald-900/40 text-emerald-300 border-emerald-800/60",
    membersCount: 38900,
    postsCount: 3410,
  },
  {
    id: "hub-03",
    category: "Food Security & Climate Resilience",
    slug: "food-security",
    description: "Agronomic innovation, drought-resistant heirloom seeds, post-harvest loss reduction, and continental food sovereignty.",
    iconName: "ShieldCheck",
    color: "bg-teal-900/40 text-teal-300 border-teal-800/60",
    membersCount: 19800,
    postsCount: 940,
  },
  {
    id: "hub-04",
    category: "Agribusiness & Continental Trade (AfCFTA)",
    slug: "agribusiness-trade",
    description: "Connecting smallholders, processors, logistics corridors, and cross-border customs solutions across Africa.",
    iconName: "TrendingUp",
    color: "bg-blue-900/40 text-blue-300 border-blue-800/60",
    membersCount: 28400,
    postsCount: 1450,
  },
  {
    id: "hub-05",
    category: "Food Technology & Cold Chain",
    slug: "food-technology",
    description: "Solar-powered cold storage, biotech fermentation, digital traceability, and solar dehydration startups.",
    iconName: "Cpu",
    color: "bg-purple-900/40 text-purple-300 border-purple-800/60",
    membersCount: 14200,
    postsCount: 680,
  },
  {
    id: "hub-06",
    category: "Food Tourism & Cultural Trails",
    slug: "food-tourism",
    description: "Mapping Africa's greatest food trails, spice plantation stays, village dining tours, and heritage markets.",
    iconName: "Compass",
    color: "bg-orange-900/40 text-orange-300 border-orange-800/60",
    membersCount: 22100,
    postsCount: 1120,
  },
  {
    id: "hub-07",
    category: "Nutrition & African Superfoods",
    slug: "nutrition-superfoods",
    description: "Scientific validation of Baobab, Moringa, Bambara groundnut, Tigernuts, and African indigenous health wellness.",
    iconName: "HeartPulse",
    color: "bg-rose-900/40 text-rose-300 border-rose-800/60",
    membersCount: 17600,
    postsCount: 890,
  },
  {
    id: "hub-08",
    category: "Culinary Arts & Master Chefs",
    slug: "culinary-arts",
    description: "Contemporary gastronomy, plating aesthetics, fine dining adaptations, and young chef mentorship programs.",
    iconName: "Award",
    color: "bg-yellow-900/40 text-yellow-300 border-yellow-800/60",
    membersCount: 31200,
    postsCount: 2190,
  },
  {
    id: "hub-09",
    category: "Food Export & Quality Standards",
    slug: "export-opportunities",
    description: "Navigating FDA, EU, and intra-African standards for value-added processed African food exports.",
    iconName: "Globe2",
    color: "bg-indigo-900/40 text-indigo-300 border-indigo-800/60",
    membersCount: 16800,
    postsCount: 780,
  },
  {
    id: "hub-10",
    category: "Investment, Grants & Venture Capital",
    slug: "investment-opportunities",
    description: "Pitching food startups, impact investment funds, diaspora angel syndicates, and government grant programs.",
    iconName: "Coins",
    color: "bg-lime-900/40 text-lime-300 border-lime-800/60",
    membersCount: 15900,
    postsCount: 620,
  },
];

export const DEMO_HUB_POSTS: HubPost[] = [
  {
    id: "post-01",
    hubId: "hub-01",
    hubSlug: "food-heritage",
    hubCategory: "Food Heritage & Ancient Grains",
    authorMemberId: "mem-01",
    authorName: "Amina Okafor",
    authorPhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    authorRole: "Culinary Historian",
    authorCountry: "Nigeria",
    title: "Why Fonio is Africa's 5,000-Year-Old Answer to Global Climate Disruption",
    body: "Fonio (Digitaria exilis) matures in as little as 6 to 8 weeks in poor, drought-prone Sahelian soils where other cereal crops fail. Rich in methionine and cystine (crucial amino acids missing in wheat and rice), its low glycemic index makes it a powerhouse superfood. Here are 3 traditional preservation techniques passed down through northern Nigerian farming cooperatives...",
    tags: ["Fonio", "Ancient Grains", "Sahel Agriculture", "Food Sovereignty"],
    likesCount: 342,
    commentsCount: 58,
    createdAt: "2025-08-14",
    imageUrl: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: "post-02",
    hubId: "hub-03",
    hubSlug: "food-security",
    hubCategory: "Food Security & Climate Resilience",
    authorMemberId: "mem-03",
    authorName: "Wanjiku Mwangi",
    authorPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    authorRole: "Continental Ambassador",
    authorCountry: "Kenya",
    title: "Policy Blueprint: How Zero-Tariff Intra-African Food Corridors Can Eliminate Regional Famine",
    body: "While one African region experiences bumper grain harvests, a neighboring territory only 400km across the border can face severe price spikes due to border delays and non-tariff barriers. Under the AfCFTA agricultural protocols being prepared for Abuja 2026, we are proposing fast-track digital green lanes for perishable indigenous crops...",
    tags: ["AfCFTA", "Food Policy", "Trade Corridors", "East Africa"],
    likesCount: 512,
    commentsCount: 94,
    createdAt: "2025-08-18",
  },
  {
    id: "post-03",
    hubId: "hub-04",
    hubSlug: "agribusiness-trade",
    hubCategory: "Agribusiness & Continental Trade",
    authorMemberId: "mem-02",
    authorName: "Kwame Mensah",
    authorPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    authorRole: "Agribusiness Entrepreneur",
    authorCountry: "Ghana",
    title: "From Raw Cocoa Beans to Artisanal Ashanti Chocolate: A 400% Value Addition Case Study",
    body: "For over a century, West Africa produced 70% of the world's raw cocoa while retaining less than 6% of the chocolate industry's global wealth. Our collective in Kumasi transitioned to in-country bean-to-bar micro-batch processing using solar roasting. Here is the operational breakdown of equipment, packaging, and shipping to Nigeria, South Africa, and Kenya...",
    tags: ["Cocoa Processing", "Value Addition", "Ghana Agribusiness", "Manufacturing"],
    likesCount: 428,
    commentsCount: 71,
    createdAt: "2025-08-20",
    imageUrl: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: "post-04",
    hubId: "hub-08",
    hubSlug: "culinary-arts",
    hubCategory: "Culinary Arts & Master Chefs",
    authorMemberId: "mem-10",
    authorName: "Fatou Diop",
    authorPhoto: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80",
    authorRole: "Master Chef",
    authorCountry: "Senegal",
    title: "Mastering the 'Sokhor' (Socarrat Crust) of Royal Senegalese Thieboudienne",
    body: "The absolute crown jewel of true Ceebu Jën is the 'Xooñ' or crispy golden caramelized bottom crust of the rice pot. It requires a precise balance of oil temperature, natural tomato sugars, and resting time over dying charcoal embers. In this breakdown, I share the exact timing cues used by Saint-Louis grandmothers...",
    tags: ["Thieboudienne", "Chef Techniques", "Senegalese Gastronomy", "Teranga"],
    likesCount: 680,
    commentsCount: 112,
    createdAt: "2025-08-22",
  },
];

