import { MarketplaceListing, Vendor } from "@/types/master-models";

export const DEMO_VENDORS: Vendor[] = [
  {
    id: "vend-01",
    memberId: "mem-05",
    businessName: "Heritage Spice Co. (Ashanti)",
    country: "Ghana",
    category: "Traditional Ingredients & Spices",
    logoUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=200&auto=format&fit=crop&q=80",
    description: "Ethically harvested forest spices, wild ashanti black pepper, sundried prekese, and handmade clay asanka grinding bowls.",
    rating: 4.98,
    isApproved: true,
    totalProducts: 14,
  },
  {
    id: "vend-02",
    memberId: "mem-06",
    businessName: "Horn of Africa Organic Exports",
    country: "Ethiopia",
    category: "Single-Origin Coffee & Ancient Grains",
    logoUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=200&auto=format&fit=crop&q=80",
    description: "Certified organic shade-grown Yirgacheffe & Sidamo specialty coffees, heritage ivory teff flour, and highland cardamom.",
    rating: 4.95,
    isApproved: true,
    totalProducts: 9,
  },
  {
    id: "vend-03",
    memberId: "mem-15",
    businessName: "Ivorian Golden Attieke Cooperative",
    country: "Côte d'Ivoire",
    category: "Food Products & Swallows",
    logoUrl: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=200&auto=format&fit=crop&q=80",
    description: "Sun-dried and pre-steamed artisanal fermented cassava couscous (Attieke) packaged in eco-friendly banana fiber bags.",
    rating: 4.91,
    isApproved: true,
    totalProducts: 6,
  },
  {
    id: "vend-04",
    memberId: "mem-11",
    businessName: "Marrakech Medina Spices & Ceramics",
    country: "Morocco",
    category: "Food Equipment & Cultural Crafts",
    logoUrl: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=200&auto=format&fit=crop&q=80",
    description: "Hand-thrown lead-free terracotta cooking tagines, pure saffron from Taliouine, and cold-pressed culinary Argan oil.",
    rating: 4.99,
    isApproved: true,
    totalProducts: 12,
  },
];

export const DEMO_MARKETPLACE_LISTINGS: MarketplaceListing[] = [
  {
    id: "prod-01",
    vendorId: "vend-02",
    vendorName: "Horn of Africa Organic Exports",
    vendorCountry: "Ethiopia",
    category: "Traditional Ingredients",
    title: "Single-Origin Yirgacheffe Heirloom Coffee Beans (1kg)",
    description: "Natural sun-dried Ethiopian heirloom coffee beans harvested at 2,200m altitude. Bursting with aromatic floral jasmine, bergamot, and sweet ripe blueberry tasting notes.",
    price: 24000,
    priceNGN: 24000,
    currency: "NGN",
    images: [
      "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80",
    ],
    stock: 45,
    rating: 4.98,
    reviewsCount: 112,
    originRegion: "Yirgacheffe, Southern Nations, Ethiopia",
    isFeatured: true,
  },
  {
    id: "prod-02",
    vendorId: "vend-01",
    vendorName: "Heritage Spice Co. (Ashanti)",
    vendorCountry: "Ghana",
    category: "Traditional Ingredients",
    title: "Ancestral 10-Spice Yaji & Suya Pepper Blend (250g Jar)",
    description: "Authentic roasted peanut powder, ginger, cloves, grains of paradise, and dried chili pepper blend stone-ground according to northern Nigerian & Ghanaian traditions.",
    price: 8500,
    priceNGN: 8500,
    currency: "NGN",
    images: [
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80",
    ],
    stock: 80,
    rating: 4.96,
    reviewsCount: 84,
    originRegion: "Ashanti Forest, Ghana",
    isFeatured: true,
  },
  {
    id: "prod-03",
    vendorId: "vend-04",
    vendorName: "Marrakech Medina Spices & Ceramics",
    vendorCountry: "Morocco",
    category: "Food Equipment",
    title: "Hand-Thrown Terracotta Cooking Tagine (12-inch)",
    description: "Authentic lead-free red clay tagine with conical steam-recirculating lid. Handcrafted by master artisans in Safi, Morocco. Suitable for slow-cooking lamb, chicken, and vegetables over gas or charcoal.",
    price: 38000,
    priceNGN: 38000,
    currency: "NGN",
    images: [
      "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&auto=format&fit=crop&q=80",
    ],
    stock: 22,
    rating: 5.0,
    reviewsCount: 41,
    originRegion: "Safi / Marrakech, Morocco",
    isFeatured: true,
  },
  {
    id: "prod-04",
    vendorId: "vend-01",
    vendorName: "Heritage Spice Co. (Ashanti)",
    vendorCountry: "Ghana",
    category: "Food Equipment",
    title: "Traditional Clay Asanka Grinding Bowl with Wooden Tapoli",
    description: "Heavy grooved earthenware earthenware mortar and carved pestle used across West Africa to grind fresh pepper sauces, tomatoes, and herbs without bruising delicate aromatic oils.",
    price: 18500,
    priceNGN: 18500,
    currency: "NGN",
    images: [
      "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=800&auto=format&fit=crop&q=80",
    ],
    stock: 35,
    rating: 4.93,
    reviewsCount: 39,
    originRegion: "Vume Pottery Village, Ghana",
    isFeatured: false,
  },
  {
    id: "prod-05",
    vendorId: "vend-03",
    vendorName: "Ivorian Golden Attieke Cooperative",
    vendorCountry: "Côte d'Ivoire",
    category: "Food Products",
    title: "Artisanal Premium Grade Dried Attieke (5x 500g Packs)",
    description: "100% naturally fermented cassava couscous. Lightweight, vacuum-sealed for long shelf-life. Rehydrates in 5 minutes with warm water to tender, fluffy, slightly tangy perfection.",
    price: 15000,
    priceNGN: 15000,
    currency: "NGN",
    images: [
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&auto=format&fit=crop&q=80",
    ],
    stock: 60,
    rating: 4.88,
    reviewsCount: 52,
    originRegion: "Grand-Bassam, Côte d'Ivoire",
    isFeatured: false,
  },
  {
    id: "prod-06",
    vendorId: "vend-04",
    vendorName: "Marrakech Medina Spices & Ceramics",
    vendorCountry: "Morocco",
    category: "Traditional Ingredients",
    title: "Taliouine Royal Red Saffron Threads (5g Certified)",
    description: "Grade-1 pure organic saffron stigmas hand-picked at dawn in the Anti-Atlas mountains. Intense floral aroma, deep golden coloring power, and therapeutic properties.",
    price: 28000,
    priceNGN: 28000,
    currency: "NGN",
    images: [
      "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    ],
    stock: 30,
    rating: 4.99,
    reviewsCount: 67,
    originRegion: "Taliouine, Morocco",
    isFeatured: true,
  },
  {
    id: "prod-07",
    vendorId: "vend-01",
    vendorName: "Heritage Spice Co. (Ashanti)",
    vendorCountry: "Ghana",
    category: "Fashion & Textiles",
    title: "Hand-Woven Authentic Kente Chef Apron & Headwrap",
    description: "Ceremonial heavy-weight cotton apron woven on historic Ashanti looms with symbolic gold, green, and maroon geometric motifs. Features reinforced pockets for culinary tools.",
    price: 22000,
    priceNGN: 22000,
    currency: "NGN",
    images: [
      "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=800&auto=format&fit=crop&q=80",
    ],
    stock: 25,
    rating: 4.95,
    reviewsCount: 33,
    originRegion: "Bonwire, Ghana",
    isFeatured: false,
  },
  {
    id: "prod-08",
    vendorId: "vend-02",
    vendorName: "Horn of Africa Organic Exports",
    vendorCountry: "Ethiopia",
    category: "Books & Publications",
    title: "Feast of 54: The Definitive Culinary Atlas of Africa (Hardcover)",
    description: "420-page collector's volume documenting 500 indigenous recipes, ancient culinary migrations, fermentation charts, and full-color photography across every African state.",
    price: 32000,
    priceNGN: 32000,
    currency: "NGN",
    images: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
    ],
    stock: 50,
    rating: 5.0,
    reviewsCount: 95,
    originRegion: "Abuja / Pan-African Edition",
    isFeatured: true,
  },
];

