import { MediaPost } from "@/types/master-models";

export const DEMO_MEDIA_POSTS: MediaPost[] = [
  {
    id: "med-01",
    category: "Festival Updates",
    title: "Abuja 2026: Eagle Square Unveils Layout for Historic 2-Kilometre African Peace Table",
    slug: "abuja-2026-eagle-square-unveils-peace-table-layout",
    summary: "Afrigreen & Heritage Concepts Limited officially reveals the diplomatic and public seating blueprints for the longest multicultural banquet table in continental history.",
    body: "The organizing committee of the African Cultural Culinary Festival (ACCF) has formally released the spatial architectural plans for the landmark 2-Kilometre African Peace Table set to anchor the Abuja 2026 festival. Spanning five thematic zones representing all geographic regions of Africa and the Diaspora, the Peace Table will seat 10,000 accredited delegates, serving over 1,000 traditional indigenous recipes in a historic show of continental solidarity.",
    mediaUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    mediaType: "article",
    publishedAt: "2025-08-10",
    readTime: "4 min read",
    author: "ACCF Media Secretariat",
    imageUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: "med-02",
    category: "Documentaries",
    title: "Watch: The Sacred Kolanut — The Ancient Ritual of Welcome and Peace",
    slug: "documentary-the-sacred-kolanut",
    summary: "An evocative visual journey through the rainforests of West Africa, exploring why the breaking of the Kolanut represents the deepest covenant of peace across African civilizations.",
    body: "In this 18-minute documentary produced in collaboration with the Heritage Trust, elders and historians from Nigeria, Benin, and Ghana explain the spiritual, social, and diplomatic significance of 'Oji' / 'Goro' / 'Kolanut'. As the saying goes: 'He who brings kolanut brings life.'",
    mediaUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    mediaType: "video",
    publishedAt: "2025-07-25",
    readTime: "18 min watch",
    author: "Heritage Visual Studios",
    imageUrl: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&auto=format&fit=crop&q=80",
    videoDuration: "18:24",
  },
  {
    id: "med-03",
    category: "Latest News",
    title: "African Union and FAO Endorse ACCF Food Security Charter Ahead of 2026 Summit",
    slug: "african-union-fao-endorse-accf-charter",
    summary: "Continental bodies join forces with ACCF to promote indigenous crop preservation, reduce agricultural trade tariffs, and mobilize diaspora impact capital.",
    body: "In a joint communique issued today in Addis Ababa, senior representatives affirmed that cultural culinary pride is fundamentally intertwined with agricultural sovereignty. The ACCF platform's digital registration of 300 million members was hailed as a transformative civic movement for continental cohesion.",
    mediaUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    mediaType: "press",
    publishedAt: "2025-08-01",
    readTime: "3 min read",
    author: "Continental Press Bureau",
    imageUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: "med-04",
    category: "Success Stories",
    title: "How Meet & Eat Africa Reconnected Diaspora Families Across 12 African Capitals",
    slug: "how-meet-and-eat-reconnected-diaspora-families",
    summary: "From London to Nairobi, New York to Lagos, members share how sharing home-cooked cultural meals restored ancestral ties and launched cross-border ventures.",
    body: "Over 1,200 cultural dining meals have already been arranged across pilot cities. In this feature, we follow Marcus from Manchester dining with Samuel in Addis Ababa, and Amina hosting culinary students from the Caribbean in Lagos...",
    mediaUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    mediaType: "article",
    publishedAt: "2025-08-15",
    readTime: "6 min read",
    author: "Chioma Adeleke",
    imageUrl: "https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?w=1200&auto=format&fit=crop&q=80",
  },
];

