import { MeetEatListing } from "@/types/master-models";

export const DEMO_MEET_EAT_LISTINGS: MeetEatListing[] = [
  {
    id: "me-01",
    hostMemberId: "mem-04",
    hostName: "Samuel Abebe",
    hostPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    country: "Ethiopia",
    city: "Addis Ababa (Bole Heritage Quarter)",
    cuisine: "Traditional Ethiopian Highland Feast",
    title: "Communal Gursha, Spiced Doro Wat & Traditional Coffee Ceremony",
    description: "Join our family courtyard under the jacaranda trees for an authentic 7-dish communal Messob feast. Experience the ancient ritual of Gursha (feeding one another as an act of fellowship) and finish with a full, unhurried Ethiopian coffee roasting ceremony over frankincense.",
    dietaryOptions: ["Vegetarian / Vegan Friendly", "Halal Certified Meat", "Gluten-Free 100% Teff"],
    maxGuests: 8,
    seatsAvailable: 3,
    priceNGN: 25000,
    date: "Every Saturday & Sunday",
    timeSlot: "17:00 – 21:00 EAT",
    images: [
      "https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
    ],
    menuHighlights: [
      "Wood-simmered Doro Wat with Farm Eggs",
      "Shiro Mitten with Garlic and Niter Kibbeh",
      "100% Heirloom Brown & Ivory Teff Injera",
      "Clay-pot Clay-Roasted Wild Sidamo Arabica Coffee",
    ],
    rating: 4.96,
    reviewsCount: 48,
    languagesSpoken: ["Amharic", "English", "Italian"],
  },
  {
    id: "me-02",
    hostMemberId: "mem-01",
    hostName: "Amina Okafor",
    hostPhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    country: "Nigeria",
    city: "Lagos (Victoria Island Rooftop)",
    cuisine: "Contemporary Coastal Nigerian Heritage",
    title: "Firewood Smoked Jollof, Suya Skewers & Ancestral Heritage Soups",
    description: "An open-air dinner overlooking the Atlantic breeze in Lagos. We explore the deep flavor architecture of smoky party jollof, hand-pounded yam with seafood egusi, and artisanal tiger nut zobo infusions while discussing Nigerian food history and cultural diplomacy.",
    dietaryOptions: ["Pescatarian", "Halal Beef", "Nut-Free Adaptable"],
    maxGuests: 10,
    seatsAvailable: 4,
    priceNGN: 35000,
    date: "Thursday & Saturday Evenings",
    timeSlot: "18:30 – 22:30 WAT",
    images: [
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80",
    ],
    menuHighlights: [
      "Lagos Firewood Jollof with Smoked Snapper",
      "Prime Beef Suya with Yaji Spice Crust",
      "Silken Pounded Yam with Wild Herb Egusi",
      "Chilled Hibiscus Zobo infused with Cloves & Pineapple",
    ],
    rating: 4.98,
    reviewsCount: 62,
    languagesSpoken: ["English", "Yoruba", "Pidgin"],
  },
  {
    id: "me-03",
    hostMemberId: "mem-10",
    hostName: "Fatou Diop",
    hostPhoto: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80",
    country: "Senegal",
    city: "Dakar (Ngor Island Beachfront)",
    cuisine: "Authentic Wolof Teranga Seafood",
    title: "The Royal Thieboudienne Bowl & Coastal Wolof Teranga",
    description: "Step into our seaside family compound on Ngor Island. We gather around the traditional royal communal platter for Ceebu Jën Penda Mbaye, breaking crusty broken jasmine rice enriched with white grouper, caramelized onions, and tamarind relish.",
    dietaryOptions: ["Pescatarian", "Gluten-Free", "Dairy-Free"],
    maxGuests: 12,
    seatsAvailable: 6,
    priceNGN: 28000,
    date: "Fridays & Sundays",
    timeSlot: "13:00 – 17:00 GMT",
    images: [
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    ],
    menuHighlights: [
      "Red Thieboudienne (Ceebu Jën) with Fresh Grouper",
      "Pastels with Fiery Smoked Tomato Piment",
      "Thiéboudienne Tamarind & Hibiscus Salad",
      "Touba Spiced Peppery Coffee Ritual",
    ],
    rating: 5.0,
    reviewsCount: 54,
    languagesSpoken: ["Wolof", "French", "English"],
  },
  {
    id: "me-04",
    hostMemberId: "mem-11",
    hostName: "Tariq El-Mansouri",
    hostPhoto: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80",
    country: "Morocco",
    city: "Marrakech (Historic Riad)",
    cuisine: "Imperial Moroccan Tagines & Pastilla",
    title: "Candlelit Riad Feast: 7-Hour Lamb Tagine & Saffron Pastilla",
    description: "Dine in the courtyard of a restored 18th-century Riad surrounded by orange blossom trees. We prepare lamb slow-braised with 35 spices (Ras el Hanout), savory sweet chicken and almond pastilla, and freshly baked anise semolina breads.",
    dietaryOptions: ["Halal", "Dairy-Free", "Nut-Free on Request"],
    maxGuests: 8,
    seatsAvailable: 2,
    priceNGN: 32000,
    date: "Wednesday through Saturday",
    timeSlot: "19:00 – 23:00 WET",
    images: [
      "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=800&auto=format&fit=crop&q=80",
    ],
    menuHighlights: [
      "Crisp Saffron Pigeon/Chicken Pastilla with Cinnamon",
      "7-Hour Braised Lamb Shoulder with Prunes and Sesame",
      "Seven Cooked Moroccan Salads (Zaalouk, Taktouka)",
      "Fresh Mint Tea with Pine Nuts and Almond Gazelle Horns",
    ],
    rating: 4.97,
    reviewsCount: 71,
    languagesSpoken: ["Arabic", "French", "English", "Amazigh"],
  },
  {
    id: "me-05",
    hostMemberId: "mem-13",
    hostName: "Zuwena Said",
    hostPhoto: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
    country: "Tanzania",
    city: "Zanzibar (Stone Town Rooftop)",
    cuisine: "Swahili Coastal Spice Island Gastronomy",
    title: "Zanzibar Sunset: Swahili Coconut Curries & Spiced Pilau",
    description: "Overlooking the dhow boats in the harbor as the sun dips into the Indian Ocean. We hand-press coconut milk to braise fresh octopus and lobster, paired with fragrant clove and cardamom pilau rice and sweet banana fritters.",
    dietaryOptions: ["Pescatarian", "Halal", "Gluten-Free"],
    maxGuests: 10,
    seatsAvailable: 5,
    priceNGN: 30000,
    date: "Tuesday, Friday, Saturday",
    timeSlot: "17:30 – 21:30 EAT",
    images: [
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    ],
    menuHighlights: [
      "Swahili Spiced Pilau with Zanzibar Beef Stew",
      "Fresh Coconut Crab and Prawn Curry",
      "Kachumbari with Green Mango and Lime Juice",
      "Zanzibar Cardamom Coffee with Halwa",
    ],
    rating: 4.95,
    reviewsCount: 39,
    languagesSpoken: ["Swahili", "English", "Arabic"],
  },
  {
    id: "me-06",
    hostMemberId: "mem-08",
    hostName: "Thabo Mokoena",
    hostPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    country: "South Africa",
    city: "Cape Town (Bo-Kaap & Table Mountain View)",
    cuisine: "Cape Malay & Fire-Cooked Braai",
    title: "The Bo-Kaap Heritage Table: Bobotie, Samosas & Fire Braai",
    description: "Set against the iconic colorful facades of Bo-Kaap. We blend centuries of Cape Malay spice trading with southern African wood-fire braai techniques. Learn to fold delicate spicy samosas and bake golden egg-custard topped Bobotie.",
    dietaryOptions: ["Halaal Friendly", "Vegetarian Options", "Nut-Free"],
    maxGuests: 10,
    seatsAvailable: 4,
    priceNGN: 29000,
    date: "Thursday & Sunday",
    timeSlot: "18:00 – 22:00 SAST",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80",
    ],
    menuHighlights: [
      "Traditional Cape Malay Baked Bobotie with Bay Leaves",
      "Crispy Cape Spiced Lamb Samosas with Blatjang",
      "Flame-Charred Boerewors & Mielie Pap with Chakalaka",
      "Cape Koesisters Rolled in Toasted Desiccated Coconut",
    ],
    rating: 4.99,
    reviewsCount: 83,
    languagesSpoken: ["English", "isiXhosa", "Afrikaans"],
  },
];

