import { Member } from "@/types/master-models";

export const DEMO_MEMBERS: Member[] = [
  // 1. Standard Member Persona
  {
    id: "mem-01",
    name: "Amina Okafor",
    email: "amina.okafor@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    country: "Nigeria",
    city: "Lagos",
    tier: "Standard",
    chairNo: "AKDT-0002548",
    joinDate: "May 2025",
    pledgeText: "Peace begins when we sit at the same table and share our ancestral heritage.",
    isVerified: true,
    role: "member",
    bio: "Culinary heritage researcher and lover of West African indigenous grains and swallows.",
    foodInterests: ["Heritage Soups", "Fonio & Ancient Grains", "Fermented Spices"],
    culturalInterests: ["Yoruba Folklore", "Pan-African Peace Initiatives", "Artisanal Pottery"],
    languages: ["English", "Yoruba", "Pidgin"],
    phone: "+234 802 345 6789",
  },
  // 2. Premium Member Persona
  {
    id: "mem-02",
    name: "Kwame Mensah",
    email: "kwame.mensah@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    country: "Ghana",
    city: "Accra",
    tier: "Premium",
    chairNo: "AKDT-0001092",
    joinDate: "January 2025",
    pledgeText: "Breaking the Kolanut is our sacred commitment to African economic fraternity.",
    isVerified: true,
    role: "business",
    bio: "Agribusiness entrepreneur connecting smallholder cocoa and plantain farmers to continental value chains.",
    foodInterests: ["Smoked Fish Delicacies", "Palm Nut Stews", "Artisanal Cocoa"],
    culturalInterests: ["Ashanti Heritage", "Intra-African Trade", "Afrobeats History"],
    languages: ["English", "Twi", "French"],
    phone: "+233 24 567 8901",
  },
  // 3. Continental Ambassador Persona
  {
    id: "mem-03",
    name: "Wanjiku Mwangi",
    email: "wanjiku.mwangi@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    country: "Kenya",
    city: "Nairobi",
    tier: "Continental Ambassador",
    chairNo: "AKDT-0000042",
    joinDate: "November 2024",
    pledgeText: "From Mount Kenya to Table Mountain, our shared food sovereignty is Africa's true shield.",
    isVerified: true,
    role: "ambassador",
    bio: "Diplomatic policy advisor on food systems and sustainable regenerative gastronomy across East Africa.",
    foodInterests: ["Indigenous Greens (Managu, Terere)", "Swahili Seafood", "Highland Tea"],
    culturalInterests: ["Kikuyu Proverbs", "African Food Sovereignty", "Cultural Diplomacy"],
    languages: ["English", "Swahili", "Kikuyu"],
    phone: "+254 712 345 678",
  },
  // 4. Cultural Host Persona
  {
    id: "mem-04",
    name: "Samuel Abebe",
    email: "samuel.abebe@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    country: "Ethiopia",
    city: "Addis Ababa",
    tier: "Standard",
    chairNo: "AKDT-0003114",
    joinDate: "March 2025",
    pledgeText: "When we feed our neighbor, we break the cycle of division and plant seeds of enduring peace.",
    isVerified: true,
    role: "host",
    isHost: true,
    bio: "Third-generation master host specializing in traditional Ethiopian Gursha rituals and wood-fired Injera.",
    foodInterests: ["Traditional Injera & Doro Wat", "Highland Spices", "Coffee Roasting Rituals"],
    culturalInterests: ["Amharic Calligraphy", "Highland Hospitality", "Ethiopian History"],
    languages: ["Amharic", "English", "Italian"],
    phone: "+251 91 123 4567",
  },
  // 5. Marketplace Vendor Persona
  {
    id: "mem-05",
    name: "Akosua Boateng",
    email: "akosua.boateng@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=400&auto=format&fit=crop&q=80",
    country: "Ghana",
    city: "Kumasi",
    tier: "Premium",
    chairNo: "AKDT-0004519",
    joinDate: "February 2025",
    pledgeText: "African crafts and culinary tools carry the spirit and hands of our ancestors.",
    isVerified: true,
    role: "vendor",
    isVendor: true,
    bio: "Founder of Heritage Spice Co., exporting single-origin Ashanti black pepper, wild herbs, and handmade clay asanka bowls.",
    foodInterests: ["Wild Forest Herbs", "Heirloom Spices", "Sun-Dried Grains"],
    culturalInterests: ["Artisanal Pottery", "Textiles (Kente)", "Fair Trade Networks"],
    languages: ["English", "Twi"],
    phone: "+233 20 987 6543",
  },
  // 6. Agribusiness / Business Member Persona
  {
    id: "mem-06",
    name: "Bethlehem Tadesse",
    email: "bethlehem.tadesse@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&auto=format&fit=crop&q=80",
    country: "Ethiopia",
    city: "Hawassa",
    tier: "Premium",
    chairNo: "AKDT-0001889",
    joinDate: "December 2024",
    pledgeText: "Trade within Africa is the strongest foundation for continental prosperity and peace.",
    isVerified: true,
    role: "business",
    bio: "Director of Horn of Africa Organic Exports, specializing in shade-grown Yirgacheffe coffee and wild cardamom.",
    foodInterests: ["Single-Origin Coffee", "Heirloom Pulses", "Teff Value Chain"],
    culturalInterests: ["Agri-Tech", "Continental Logistics", "Export Quality Standards"],
    languages: ["Amharic", "English", "Oromo"],
    phone: "+251 92 345 6789",
  },
  // 7. Event Participant Persona
  {
    id: "mem-07",
    name: "Sandrine Mugabo",
    email: "sandrine.mugabo@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
    country: "Rwanda",
    city: "Kigali",
    tier: "Standard",
    chairNo: "AKDT-0005230",
    joinDate: "June 2025",
    pledgeText: "One continent, one table, one future. May our food heal every memory of division.",
    isVerified: true,
    role: "member",
    bio: "Youth food innovation leader and delegate to the ACCF Abuja 2026 Food Security Summit.",
    foodInterests: ["Rwandan Akabanga Chili", "Lake Kivu Tilapia", "Volcanic Soil Coffee"],
    culturalInterests: ["Youth Agri-Leadership", "Culinary Storytelling", "Peace Building"],
    languages: ["Kinyarwanda", "French", "English"],
    phone: "+250 788 123 456",
  },
  // 8. Community Moderator Persona
  {
    id: "mem-08",
    name: "Thabo Mokoena",
    email: "thabo.mokoena@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    country: "South Africa",
    city: "Cape Town",
    tier: "Premium",
    chairNo: "AKDT-0000880",
    joinDate: "October 2024",
    pledgeText: "Ubuntu: I am because we eat together and honor the soil of Africa.",
    isVerified: true,
    role: "moderator",
    bio: "Food anthropologist and ACCF community steward facilitating constructive dialogue across African hubs.",
    foodInterests: ["Cape Malay Curries", "Indigenous Rooibos", "Wild Foraging"],
    culturalInterests: ["Ubuntu Philosophy", "Community Moderation", "Heritage Archiving"],
    languages: ["English", "isiXhosa", "Afrikaans"],
    phone: "+27 82 345 6789",
  },
  // 9. Platform Administrator Persona
  {
    id: "mem-09",
    name: "Dr. Alimatu Bello",
    email: "admin@africanculinaryfestival.africa",
    photoUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80",
    country: "Nigeria",
    city: "Abuja",
    tier: "Continental Ambassador",
    chairNo: "AKDT-0000001",
    joinDate: "September 2024",
    pledgeText: "Breaking the Kolanut is the covenant of peace that will unite our 54 nations forever.",
    isVerified: true,
    role: "admin",
    bio: "Executive Program Director, Afrigreen & Heritage Concepts Limited / ACCF Abuja 2026.",
    foodInterests: ["Continental Culinary Diplomacy", "Traditional Fermentation", "Ancient Grains"],
    culturalInterests: ["Pan-African Institutions", "Heritage Preservation", "Diplomatic Protocol"],
    languages: ["English", "Hausa", "French"],
    phone: "+234 805 123 4567",
  },
  // Additional diverse members across Africa
  {
    id: "mem-10",
    name: "Fatou Diop",
    email: "fatou.diop@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80",
    country: "Senegal",
    city: "Dakar",
    tier: "Continental Ambassador",
    chairNo: "AKDT-0000128",
    joinDate: "January 2025",
    pledgeText: "Teranga: The sacred Senegalese duty of unconditional hospitality for every African brother and sister.",
    isVerified: true,
    role: "host",
    isHost: true,
    bio: "Master chef and cultural ambassador of Senegalese Thieboudienne and coastal Wolof cuisine.",
    foodInterests: ["Thieboudienne", "Bissap & Tamarind", "Millet Couscous"],
    culturalInterests: ["Teranga Hospitality", "Sufi Music", "Maritime Culture"],
    languages: ["Wolof", "French", "English"],
  },
  {
    id: "mem-11",
    name: "Tariq El-Mansouri",
    email: "tariq.mansouri@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80",
    country: "Morocco",
    city: "Marrakech",
    tier: "Premium",
    chairNo: "AKDT-0001402",
    joinDate: "March 2025",
    pledgeText: "In the aroma of saffron, cumin, and mint, North and Sub-Saharan Africa discover their unbroken bond.",
    isVerified: true,
    role: "host",
    isHost: true,
    bio: "Heritage tagine master and spice merchant from the historic Medina of Marrakech.",
    foodInterests: ["Slow-Cooked Tagines", "Ras el Hanout Blends", "Argan Oil Gastronomy"],
    culturalInterests: ["Amazigh Traditions", "Spice Route History", "Andalusian Architecture"],
    languages: ["Arabic", "French", "English", "Amazigh"],
  },
  {
    id: "mem-12",
    name: "Youssef Hassan",
    email: "youssef.hassan@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    country: "Egypt",
    city: "Cairo",
    tier: "Standard",
    chairNo: "AKDT-0003882",
    joinDate: "April 2025",
    pledgeText: "The river Nile connects us all; its waters nourished the first harvests of human civilization.",
    isVerified: true,
    role: "member",
    bio: "Heritage baker restoring ancient Emmer wheat and traditional Egyptian baladi sourdoughs.",
    foodInterests: ["Ancient Grains", "Koshari Variations", "Date Molasses Pastries"],
    culturalInterests: ["Nile Valley Agronomy", "Nubian Heritage", "Culinary History"],
    languages: ["Arabic", "English"],
  },
  {
    id: "mem-13",
    name: "Zuwena Said",
    email: "zuwena.said@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
    country: "Tanzania",
    city: "Zanzibar",
    tier: "Premium",
    chairNo: "AKDT-0002100",
    joinDate: "February 2025",
    pledgeText: "The spices of Zanzibar are Africa's aromatic gift to the tables of the world.",
    isVerified: true,
    role: "host",
    isHost: true,
    bio: "Master of Swahili coastal cuisine, coconut curries, and clove plantation culinary tours.",
    foodInterests: ["Swahili Biryani", "Coconut Octopus Stew", "Cardamom & Vanilla Extracts"],
    culturalInterests: ["Dhow Navigation", "Swahili Poetry", "Spice Island Heritage"],
    languages: ["Swahili", "English", "Arabic"],
  },
  {
    id: "mem-14",
    name: "Jean-Pierre Nguema",
    email: "jean.nguema@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    country: "Cameroon",
    city: "Douala",
    tier: "Standard",
    chairNo: "AKDT-0006712",
    joinDate: "May 2025",
    pledgeText: "In Ndolé and plantains, Central Africa celebrates resilience, community and solidarity.",
    isVerified: true,
    role: "member",
    bio: "Chef and champion of wild forest foraging in the Congo Basin eco-region.",
    foodInterests: ["Ndolé Heritage", "Wild Penja Pepper", "Cassava Gastronomy"],
    culturalInterests: ["Bantu Traditions", "Forest Ecology", "Afro-Jazz"],
    languages: ["French", "English", "Duala"],
  },
  {
    id: "mem-15",
    name: "Koffi Assi",
    email: "koffi.assi@accf-demo.africa",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    country: "Côte d'Ivoire",
    city: "Abidjan",
    tier: "Standard",
    chairNo: "AKDT-0004921",
    joinDate: "March 2025",
    pledgeText: "When we share Attieke and grilled fish, no border can keep our people apart.",
    isVerified: true,
    role: "vendor",
    isVendor: true,
    bio: "Producer of certified organic artisanal Attieke and Ivorian fermented cassava couscous.",
    foodInterests: ["Attieke Production", "Spicy Grilled Fish", "Alloco & Ginger Juices"],
    culturalInterests: ["Baoule Arts", "West African Music", "Culinary Export"],
    languages: ["French", "Baoule", "English"],
  },
];

