import { PeaceWallEntry } from "@/types/master-models";

export const DEMO_PEACE_WALL_ENTRIES: PeaceWallEntry[] = [
  {
    id: "pw-01",
    memberId: "mem-01",
    guestName: "Amina Okafor",
    authorPhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    country: "Nigeria",
    message: "Peace begins when we sit at the same table and share what we have harvested from our common soil.",
    isApproved: true,
    likesCount: 248,
    createdAt: "2025-08-01",
  },
  {
    id: "pw-02",
    memberId: "mem-02",
    guestName: "Kwame Mensah",
    authorPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    country: "Ghana",
    message: "Breaking The Kolanut. Building Africa. One table, 54 nations, one shared destiny.",
    isApproved: true,
    likesCount: 195,
    createdAt: "2025-08-02",
  },
  {
    id: "pw-03",
    memberId: "mem-03",
    guestName: "Ambassador Wanjiku Mwangi",
    authorPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    country: "Kenya",
    message: "Food has no borders. When we nourish each other, we disarm every prejudice.",
    isApproved: true,
    likesCount: 382,
    createdAt: "2025-08-04",
  },
  {
    id: "pw-04",
    memberId: "mem-04",
    guestName: "Samuel Abebe",
    authorPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    country: "Ethiopia",
    message: "One Continent. One Meal. One Peace Movement. May our children inherit an Africa united in brotherhood.",
    isApproved: true,
    likesCount: 210,
    createdAt: "2025-08-06",
  },
  {
    id: "pw-05",
    memberId: "mem-10",
    guestName: "Chef Fatou Diop",
    authorPhoto: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80",
    country: "Senegal",
    message: "Teranga teaches us that there is always room for one more guest at the African bowl.",
    isApproved: true,
    likesCount: 174,
    createdAt: "2025-08-09",
  },
  {
    id: "pw-06",
    memberId: "mem-08",
    guestName: "Thabo Mokoena",
    authorPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    country: "South Africa",
    message: "Ubuntu is not a philosophy to be spoken, but a meal to be eaten together in peace.",
    isApproved: true,
    likesCount: 318,
    createdAt: "2025-08-12",
  },
  {
    id: "pw-07",
    memberId: "mem-11",
    guestName: "Tariq El-Mansouri",
    authorPhoto: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80",
    country: "Morocco",
    message: "In every grain of couscous and every pinch of saffron, North and South Africa beat with one heart.",
    isApproved: true,
    likesCount: 162,
    createdAt: "2025-08-15",
  },
  {
    id: "pw-08",
    guestName: "Kofi Annan Heritage Fellow",
    country: "Côte d'Ivoire",
    message: "Let the aroma of our traditional kitchens drown out the noise of conflict across our continent.",
    isApproved: true,
    likesCount: 144,
    createdAt: "2025-08-18",
  },
];

