import { Sponsor } from "@/types/master-models";

export const DEMO_SPONSORS: Sponsor[] = [
  {
    id: "sp-01",
    companyName: "African Union Agribusiness & Heritage Development",
    tier: "Platinum Partner",
    priceNGN: 1000000000,
    priceFormatted: "₦1,000,000,000",
    logoUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=300&auto=format&fit=crop&q=80",
    country: "Pan-African / Addis Ababa",
    description: "Official Continental Strategic Peace & Food Security Partner.",
    websiteUrl: "https://au.int",
    contactEmail: "partnerships@au.int",
    benefits: [
      "Access to 300 Million Africans Across 54 Nations",
      "Exclusive Co-Branding on 2-Kilometre Peace Table",
      "Head of Delegation Keynote at Food Security Summit",
      "Prime Exhibition Pavilion (1,000 sqm at Eagle Square)",
      "Dedicated Ministerial Diplomatic Bilateral Lounges",
      "Permanent Platinum Arch on the Digital Kolanut Tree",
    ],
  },
  {
    id: "sp-02",
    companyName: "Federal Ministry of Agriculture and Food Security (Nigeria)",
    tier: "Diamond Partner",
    priceNGN: 850000000,
    priceFormatted: "₦850,000,000",
    logoUrl: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=300&auto=format&fit=crop&q=80",
    country: "Nigeria",
    description: "Host Nation Sovereign Partnership & Agricultural Leadership.",
    websiteUrl: "https://agriculture.gov.ng",
    contactEmail: "info@agriculture.gov.ng",
    benefits: [
      "Host Nation Ceremonial Representation",
      "High-Level Policy Roundtable Sponsorship",
      "National Farmers Cooperative Pavilion",
      "Prime TV & Broadcast Prime-Time Mentions",
      "VIP Diplomatic Box for 50 Dignitaries",
    ],
  },
  {
    id: "sp-03",
    companyName: "Pan-African Green Agro-Tech Consortium",
    tier: "Gold Partner",
    priceNGN: 500000000,
    priceFormatted: "₦500,000,000",
    logoUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=300&auto=format&fit=crop&q=80",
    country: "Kenya",
    description: "Green Energy & Solar Cold-Chain Continental Sponsor.",
    websiteUrl: "https://greenagrotech.africa",
    contactEmail: "sponsor@greenagrotech.africa",
    benefits: [
      "Brand Visibility Across All Digital & Physical Hubs",
      "Exclusive Solar Technology Showcase in Cultural Village",
      "VIP Passes for 25 Corporate Executives",
      "Featured Partner Story in Media Center",
    ],
  },
  {
    id: "sp-04",
    companyName: "Heritage Bank & Trade Capital Africa",
    tier: "Silver Partner",
    priceNGN: 250000000,
    priceFormatted: "₦250,000,000",
    logoUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=300&auto=format&fit=crop&q=80",
    country: "South Africa",
    description: "Official Intra-African Trade Settlement & Finance Partner.",
    websiteUrl: "https://heritagebank.africa",
    contactEmail: "trade@heritagebank.africa",
    benefits: [
      "Exclusive Branding of Business Network & B2B Matchmaking Arena",
      "VIP Hospitality Package for 15 Guests",
      "Corporate Leaf Marker on Digital Kolanut Tree",
    ],
  },
  {
    id: "sp-05",
    companyName: "Sahara Eco-Logistics & Cold Transport",
    tier: "Bronze Partner",
    priceNGN: 150000000,
    priceFormatted: "₦150,000,000",
    logoUrl: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=300&auto=format&fit=crop&q=80",
    country: "Morocco",
    description: "Official Food Logistics & Supply Corridor Sponsor.",
    websiteUrl: "https://saharalogistics.ma",
    contactEmail: "corporate@saharalogistics.ma",
    benefits: [
      "Logo on Official Festival Program & Website Footer",
      "Exhibition Booth in Trade Concourse",
      "10 General & VIP Festival Registrations",
    ],
  },
];

