import { MembershipTier } from "@/types/master-models";

export const DEMO_MEMBERSHIP_TIERS: MembershipTier[] = [
  {
    id: "tier-standard",
    name: "Standard",
    priceNGN: 20000,
    priceFormatted: "₦20,000",
    period: "Year · Per Seat",
    badgeLabel: "Standard Peace Seat",
    benefits: [
      "Official Digital Membership Badge",
      "Personalized Profile & Chair Number (AKDT-000XXXX)",
      "Permanent Leaf on the African Kolanut Digital Tree",
      "Access to Meet & Eat Cultural Exchange Network",
      "Access to Africa Food Movement Community Hubs",
      "Festival 2026 Ticket Discounts & Priority Booking",
      "Verified Digital Peace Ambassador Certificate",
      "Voting Rights on Community Peace Initiatives",
    ],
    isPopular: false,
    colorScheme: "border-accf-line bg-accf-charcoal-card text-accf-ivory",
  },
  {
    id: "tier-premium",
    name: "Premium",
    priceNGN: 50000,
    priceFormatted: "₦50,000",
    period: "Year · Per Seat",
    badgeLabel: "VIP Continental Seat",
    benefits: [
      "Everything included in Standard Tier",
      "VIP Festival 2026 Access & Dedicated Fast-Track Entry",
      "Priority Matchmaking in Meet & Eat Cultural Exchange",
      "Full Access to Africa Business Network & B2B Directory",
      "Exclusive Discounts across the Africa Marketplace",
      "Featured Member Spotlight in ACCF Media Center",
      "Invitation to Private Masterclasses with Renowned African Chefs",
      "Golden Digital ID Card with Embossed Seal",
    ],
    isPopular: true,
    colorScheme: "border-accf-gold bg-accf-green-deep text-accf-ivory ring-1 ring-accf-gold",
  },
  {
    id: "tier-ambassador",
    name: "Continental Ambassador",
    priceNGN: 100000,
    priceFormatted: "₦100,000",
    period: "Year · Per Seat",
    badgeLabel: "Diplomatic Crest Seat",
    benefits: [
      "Everything included in Premium Tier",
      "Official Continental Peace Ambassador Diplomatic Title",
      "Exclusive Access to High-Level Leadership & Policy Forums",
      "Invitation to the Flagship 2-Kilometre Peace Table Banquet",
      "VIP Pass to the Peace Dinner & Kolanut Ceremony in Abuja",
      "Permanent Prominent Plaque on the Digital Kolanut Tree",
      "Direct Networking with Ministers, Diplomats, & Agribusiness Leaders",
      "Personalized Ceremonial Brass Digital Chair Representation",
    ],
    isPopular: false,
    colorScheme: "border-accf-gold bg-gradient-to-b from-accf-charcoal-card to-accf-green-deep text-accf-ivory ring-2 ring-accf-gold",
  },
];

