import { TreeLeaf } from "@/types/master-models";

export const DEMO_TREE_LEAVES: TreeLeaf[] = [
  {
    id: "leaf-01",
    memberId: "mem-01",
    memberName: "Amina Okafor",
    chairNo: "AKDT-0002548",
    pledgeText: "Peace begins when we sit at the same table and share our ancestral heritage.",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    country: "Nigeria",
    region: "West Africa",
    createdAt: "2025-05-12",
    leafType: "gold",
  },
  {
    id: "leaf-02",
    memberId: "mem-02",
    memberName: "Kwame Mensah",
    chairNo: "AKDT-0001092",
    pledgeText: "Breaking the Kolanut is our sacred commitment to African economic fraternity.",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    country: "Ghana",
    region: "West Africa",
    createdAt: "2025-01-20",
    leafType: "emerald",
  },
  {
    id: "leaf-03",
    memberId: "mem-03",
    memberName: "Wanjiku Mwangi",
    chairNo: "AKDT-0000042",
    pledgeText: "From Mount Kenya to Table Mountain, our shared food sovereignty is Africa's true shield.",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    country: "Kenya",
    region: "East Africa",
    createdAt: "2024-11-15",
    leafType: "gold",
  },
  {
    id: "leaf-04",
    memberId: "mem-04",
    memberName: "Samuel Abebe",
    chairNo: "AKDT-0003114",
    pledgeText: "When we feed our neighbor, we break the cycle of division and plant seeds of enduring peace.",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    country: "Ethiopia",
    region: "East Africa",
    createdAt: "2025-03-08",
    leafType: "green",
  },
  {
    id: "leaf-05",
    memberId: "mem-05",
    memberName: "Akosua Boateng",
    chairNo: "AKDT-0004519",
    pledgeText: "African crafts and culinary tools carry the spirit and hands of our ancestors.",
    photoUrl: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=400&auto=format&fit=crop&q=80",
    country: "Ghana",
    region: "West Africa",
    createdAt: "2025-02-14",
    leafType: "emerald",
  },
  {
    id: "leaf-06",
    memberId: "mem-06",
    memberName: "Bethlehem Tadesse",
    chairNo: "AKDT-0001889",
    pledgeText: "Trade within Africa is the strongest foundation for continental prosperity and peace.",
    photoUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&auto=format&fit=crop&q=80",
    country: "Ethiopia",
    region: "East Africa",
    createdAt: "2024-12-05",
    leafType: "gold",
  },
  {
    id: "leaf-07",
    memberId: "mem-07",
    memberName: "Sandrine Mugabo",
    chairNo: "AKDT-0005230",
    pledgeText: "One continent, one table, one future. May our food heal every memory of division.",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
    country: "Rwanda",
    region: "East Africa",
    createdAt: "2025-06-01",
    leafType: "green",
  },
  {
    id: "leaf-08",
    memberId: "mem-08",
    memberName: "Thabo Mokoena",
    chairNo: "AKDT-0000880",
    pledgeText: "Ubuntu: I am because we eat together and honor the soil of Africa.",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    country: "South Africa",
    region: "Southern Africa",
    createdAt: "2024-10-28",
    leafType: "gold",
  },
  {
    id: "leaf-09",
    memberId: "mem-10",
    memberName: "Fatou Diop",
    chairNo: "AKDT-0000128",
    pledgeText: "Teranga is our gift to the world: open doors, generous bowls, and unbroken peace.",
    photoUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80",
    country: "Senegal",
    region: "West Africa",
    createdAt: "2025-01-14",
    leafType: "gold",
  },
  {
    id: "leaf-10",
    memberId: "mem-11",
    memberName: "Tariq El-Mansouri",
    chairNo: "AKDT-0001402",
    pledgeText: "In the aroma of saffron, cumin, and mint, North and Sub-Saharan Africa discover their unbroken bond.",
    photoUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80",
    country: "Morocco",
    region: "North Africa",
    createdAt: "2025-03-22",
    leafType: "emerald",
  },
  {
    id: "leaf-11",
    memberId: "mem-12",
    memberName: "Youssef Hassan",
    chairNo: "AKDT-0003882",
    pledgeText: "The river Nile connects us all; its waters nourished the first harvests of human civilization.",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    country: "Egypt",
    region: "North Africa",
    createdAt: "2025-04-18",
    leafType: "green",
  },
  {
    id: "leaf-12",
    memberId: "mem-13",
    memberName: "Zuwena Said",
    chairNo: "AKDT-0002100",
    pledgeText: "The spices of Zanzibar are Africa's aromatic gift to the tables of the world.",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
    country: "Tanzania",
    region: "East Africa",
    createdAt: "2025-02-28",
    leafType: "emerald",
  },
  {
    id: "leaf-13",
    memberId: "mem-14",
    memberName: "Jean-Pierre Nguema",
    chairNo: "AKDT-0006712",
    pledgeText: "In Ndolé and plantains, Central Africa celebrates resilience, community and solidarity.",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    country: "Cameroon",
    region: "Central Africa",
    createdAt: "2025-05-04",
    leafType: "green",
  },
  {
    id: "leaf-14",
    memberId: "mem-15",
    memberName: "Koffi Assi",
    chairNo: "AKDT-0004921",
    pledgeText: "When we share Attieke and grilled fish, no border can keep our people apart.",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    country: "Côte d'Ivoire",
    region: "West Africa",
    createdAt: "2025-03-30",
    leafType: "emerald",
  },
  {
    id: "leaf-15",
    memberId: "mem-16",
    memberName: "Tendai Moyo",
    chairNo: "AKDT-0007812",
    pledgeText: "Breaking the Kolanut reminds us that African peace is an everyday culinary practice.",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    country: "Zimbabwe",
    region: "Southern Africa",
    createdAt: "2025-06-11",
    leafType: "gold",
  },
  {
    id: "leaf-16",
    memberId: "mem-17",
    memberName: "Nathalie Kaboré",
    chairNo: "AKDT-0008431",
    pledgeText: "Our ancient grains hold the answers to food security, sovereignty, and continental harmony.",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    country: "Benin",
    region: "West Africa",
    createdAt: "2025-07-02",
    leafType: "green",
  },
  {
    id: "leaf-17",
    memberId: "mem-18",
    memberName: "Marcus Garvey Johnson",
    chairNo: "AKDT-0009110",
    pledgeText: "From the African Diaspora in London, we return to the root and break the sacred Kolanut for unity.",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    country: "Diaspora (UK)",
    region: "Diaspora",
    createdAt: "2025-07-19",
    leafType: "gold",
  },
  {
    id: "leaf-18",
    memberId: "mem-19",
    memberName: "Dr. Nia Washington",
    chairNo: "AKDT-0009540",
    pledgeText: "Connecting African-American soul food to West African soil is our journey of homecoming.",
    photoUrl: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=400&auto=format&fit=crop&q=80",
    country: "Diaspora (USA)",
    region: "Diaspora",
    createdAt: "2025-08-01",
    leafType: "gold",
  },
];

